// Shared app UI class tokens, built on the semantic utilities from index.css.
// z-index scale: scrims z-60 < panels z-70 < popovers/menus z-80 < dialogs z-90.
// (The auto-hiding reader header stays z-50; the reader panel resize handle stays z-10.)
export const iconButtonClass = 'flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-muted transition-colors duration-150 ease-out hover:bg-surface-muted hover:text-ink active:scale-[0.96] disabled:pointer-events-none disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-softer'
export const roundIconButtonClass = 'flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-muted transition-colors duration-150 ease-out hover:bg-surface-muted hover:text-ink active:scale-[0.96] disabled:pointer-events-none disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-softer'
export const toolbarButtonClass = 'inline-flex h-8 items-center justify-center gap-1.5 rounded-lg px-3 text-ui-md font-medium text-ink-soft transition-colors duration-150 ease-out hover:bg-surface-muted hover:text-ink active:scale-[0.96] disabled:pointer-events-none disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-softer'
export const primaryButtonClass = 'inline-flex h-8 items-center justify-center gap-1.5 rounded-lg bg-accent px-3 text-ui-md font-medium text-accent-contrast transition-colors duration-150 ease-out hover:bg-accent-hover active:scale-[0.96] disabled:pointer-events-none disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-softer'
export const menuRowClass = 'flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-ui-md text-ink-soft transition-colors duration-150 ease-out hover:bg-surface-muted hover:text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-softer'
export const inputClass = 'min-w-0 rounded-lg border border-line-strong bg-surface px-2.5 py-2 text-ui-md text-ink outline-none transition placeholder:text-muted focus:border-accent focus-visible:ring-2 focus-visible:ring-accent-softer'
